language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install .
  - pip install -r requirements.txt
script: python main.py
